### ISSUE TITLE
Error en grafico de balance

### ISSUE THREAD

**Issue by alvarorameau** [ORT-FIS-202108/proyecto-grupo1-steinfeld-rameau#28]
Cuando se ingresa un movimiento con fecha (01/11/2021) en el grafico de balance aparece en octubre y no en noviembre

**Comment by stellaasteinfeld** [comment]
Revisamos el bug y es por el programa con el que se estaba abriendo el archivo, es un .xsl lo que se descarga por ende se tiene que abrir con excel 
![image](https://user-images.githubusercontent.com/32656632/142782672-9c2b000c-08d8-40be-920d-f062562d09f5.png)
